- name: Update All Packages
  hosts: "{{ target_hosts }}"
  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Clean up cached packages
      ansible.builtin.dnf:
        name: "*"
        state: absent
        autoremove: true
        clean_requirements_on_remove: true
